### ISSUE TITLE
Is these 3 strains recombinantions?

### ISSUE THREAD

**Issue by liamxg** [clifmckee/thai-bats-bartonella#4]
<img width="821" alt="image" src="https://github.com/clifmckee/thai-bats-bartonella/assets/46078579/ac39c972-39dd-48a8-ae8a-4fd342266515">

**Comment by clifmckee** [comment]
Yes, that is the inference that the STRUCTURE program made. For KP287a and KP174, we could tell from the individual gene sequences that these strains were recombinant because one gene clustered with a different lineage than the other genes. So the percent recombinant in this image reflects the relative length of that recombinant gene sequence. For CR224, STRUCTURE identified recombination with the Tm lineage, but it might have also been recombination with some other unidentified lineage.

**Comment by liamxg** [comment]
@clifmckee that's really cool! Is there any script for plotting recombination, x = genome position, y = recombination strains, top is the reference strain.

**Comment by clifmckee** [comment]
I didn't write anything like that for the paper, but there are probably multiple ways of doing it with `ggplot`.

**Comment by liamxg** [comment]
great, do you know any good of this, thanks.
